In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
animals = pd.read_csv('horse.csv')

In [3]:
animals.head()

surgery    age  hospital_number  rectal_temp  pulse  respiratory_rate  \
0      no  adult           530101         38.5   66.0              28.0   
1     yes  adult           534817         39.2   88.0              20.0   
2      no  adult           530334         38.3   40.0              24.0   
3     yes  young          5290409         39.1  164.0              84.0   
4      no  adult           530255         37.3  104.0              35.0   

  temp_of_extremities peripheral_pulse mucous_membrane capillary_refill_time  \
0                cool          reduced             NaN            more_3_sec   
1                 NaN              NaN   pale_cyanotic            less_3_sec   
2              normal           normal       pale_pink            less_3_sec   
3                cold           normal   dark_cyanotic            more_3_sec   
4                 NaN              NaN   dark_cyanotic            more_3_sec   

   ... packed_cell_volume total_protein abdomo_appearance abdomo_protein  \
0  ...               45.0           8.4               NaN            NaN   
1  ...               50.0          85.0            cloudy            2.0   
2  ...               33.0           6.7               NaN            NaN   
3  ...               48.0           7.2     serosanguious            5.3   
4  ...               74.0           7.4               NaN            NaN   

      outcome  surgical_lesion lesion_1 lesion_2  lesion_3  cp_data  
0        died               no    11300        0         0       no  
1  euthanized               no     2208        0         0       no  
2       lived               no        0        0         0      yes  
3        died              yes     2208        0         0      yes  
4        died               no     4300        0         0       no  

[5 rows x 28 columns]

In [4]:
target = animals['outcome']

In [5]:
target.unique()

array(['died', 'euthanized', 'lived'], dtype=object)

In [7]:
animals = animals.drop(['outcome'], axis=1)
animals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   surgery                299 non-null    object 
 1   age                    299 non-null    object 
 2   hospital_number        299 non-null    int64  
 3   rectal_temp            239 non-null    float64
 4   pulse                  275 non-null    float64
 5   respiratory_rate       241 non-null    float64
 6   temp_of_extremities    243 non-null    object 
 7   peripheral_pulse       230 non-null    object 
 8   mucous_membrane        252 non-null    object 
 9   capillary_refill_time  267 non-null    object 
 10  pain                   244 non-null    object 
 11  peristalsis            255 non-null    object 
 12  abdominal_distention   243 non-null    object 
 13  nasogastric_tube       195 non-null    object 
 14  nasogastric_reflux     193 non-null    object 
 15  nasoga

In [9]:
# decision tree does not work well with categorical variables
cat_variables = ['surgery', 'age', 'temp_of_extremities', 'peripheral_pulse', 'mucous_membrane', 
                'capillary_refill_time', 'pain', 'peristalsis', 'abdominal_distention', 
                'nasogastric_tube', 'nasogastric_reflux', 'rectal_exam_feces', 'abdomen', 
                'abdomo_appearance', 'surgical_lesion', 'cp_data']
for category in cat_variables:
    animals[category] = pd.get_dummies(animals[category])

In [10]:
animals.head()

surgery  age  hospital_number  rectal_temp  pulse  respiratory_rate  \
0        1    1           530101         38.5   66.0              28.0   
1        0    1           534817         39.2   88.0              20.0   
2        1    1           530334         38.3   40.0              24.0   
3        0    0          5290409         39.1  164.0              84.0   
4        1    1           530255         37.3  104.0              35.0   

   temp_of_extremities  peripheral_pulse  mucous_membrane  \
0                    0                 0                0   
1                    0                 0                0   
2                    0                 0                0   
3                    1                 0                0   
4                    0                 0                0   

   capillary_refill_time  ...  abdomen  packed_cell_volume  total_protein  \
0                      0  ...        1                45.0            8.4   
1                      0  ...        0                50.0           85.0   
2                      0  ...        0                33.0            6.7   
3                      0  ...        0                48.0            7.2   
4                      0  ...        0                74.0            7.4   

   abdomo_appearance  abdomo_protein  surgical_lesion  lesion_1  lesion_2  \
0                  0             NaN                1     11300         0   
1                  0             2.0                1      2208         0   
2                  0             NaN                1         0         0   
3                  0             5.3                0      2208         0   
4                  0             NaN                1      4300         0   

   lesion_3  cp_data  
0         0        1  
1         0        1  
2         0        0  
3         0        0  
4         0        1  

[5 rows x 27 columns]

In [12]:
# import train_test_split & LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [13]:
animals.values

array([[1.00000e+00, 1.00000e+00, 5.30101e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [0.00000e+00, 1.00000e+00, 5.34817e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.30334e+05, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       ...,
       [0.00000e+00, 1.00000e+00, 5.29386e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [0.00000e+00, 1.00000e+00, 5.30612e+05, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [0.00000e+00, 1.00000e+00, 5.34618e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00]])

In [14]:
target.values

array(['died', 'euthanized', 'lived', 'died', 'died', 'lived', 'lived',
       'died', 'euthanized', 'lived', 'lived', 'lived', 'lived', 'died',
       'lived', 'died', 'died', 'lived', 'lived', 'lived', 'lived',
       'lived', 'lived', 'lived', 'lived', 'lived', 'lived', 'lived',
       'died', 'lived', 'died', 'euthanized', 'lived', 'lived', 'lived',
       'euthanized', 'euthanized', 'lived', 'lived', 'died', 'died',
       'lived', 'lived', 'euthanized', 'euthanized', 'died', 'lived',
       'lived', 'died', 'died', 'lived', 'died', 'lived', 'lived',
       'euthanized', 'died', 'lived', 'died', 'died', 'died', 'lived',
       'lived', 'died', 'euthanized', 'lived', 'lived', 'lived', 'lived',
       'lived', 'lived', 'euthanized', 'lived', 'died', 'died', 'died',
       'euthanized', 'lived', 'lived', 'died', 'lived', 'died', 'lived',
       'lived', 'died', 'lived', 'lived', 'died', 'euthanized', 'lived',
       'lived', 'lived', 'died', 'lived', 'died', 'lived', 'lived',
       

In [15]:
X,y = animals.values, target.values

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y) # encode cat values to 0-1

# split data set to train, test
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1)

In [16]:
from sklearn.tree import DecisionTreeClassifier
print(X_train.shape)

(239, 27)


In [22]:
import numpy as np

In [23]:
# import imputer to address missing datasets
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
X_train = imp.fit_transform(X_train)
X_test = imp.fit_transform(X_test)

In [24]:
# fit decision tree on training data
classifier = DecisionTreeClassifier()

In [35]:
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [36]:
# predictions on test set
pred = classifier.predict(X_test)

# confusion matrix
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, pred))

# classification report
print(classification_report(y_test, pred))

[[ 6  8  6]
 [ 0  5  2]
 [ 8  2 23]]
              precision    recall  f1-score   support

           0       0.43      0.30      0.35        20
           1       0.33      0.71      0.45         7
           2       0.74      0.70      0.72        33

    accuracy                           0.57        60
   macro avg       0.50      0.57      0.51        60
weighted avg       0.59      0.57      0.57        60



In [37]:
# RandomForestClassifier will give better results because it is an ensemble of decision trees.
from sklearn.ensemble import RandomForestClassifier

In [38]:
rf_classifier = RandomForestClassifier()

In [39]:
rf_classifier.fit(X_train, y_train)

rf_pred = rf_classifier.predict(X_test)

print(confusion_matrix(y_test, rf_pred))
print(classification_report(y_test, rf_pred))

[[10  0 10]
 [ 0  0  7]
 [ 1  0 32]]
              precision    recall  f1-score   support

           0       0.91      0.50      0.65        20
           1       0.00      0.00      0.00         7
           2       0.65      0.97      0.78        33

    accuracy                           0.70        60
   macro avg       0.52      0.49      0.48        60
weighted avg       0.66      0.70      0.64        60



/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
