In [1]:
import numpy as np

In [2]:
#addition
np.add(45,20)

65

In [3]:
#subtraction
np.subtract(45,20)

25

In [4]:
# ndarray multiplication
# create ndarray which contains number of hrs worked for 5 days
# hourly rate is 15 USD

hrs_worked_per_day = np.array([8,7,9,6,8])

In [5]:
#print hourly rate for each day
hrs_worked_per_day * 15

array([120, 105, 135,  90, 120])

In [6]:
#total earning after 5 days
sum(hrs_worked_per_day * 15)

570

In [7]:
#comparison operations
#create ndarrary for weekly hrs, 5 consecutive weeks hrs data
np_weekly_hrs = np.array([43,50,30,40,37])

In [8]:
#week with more than 40 hours
np_weekly_hrs[np_weekly_hrs > 40]

array([43, 50])

In [9]:
#week with not equal to 40 hrs
np_weekly_hrs[np_weekly_hrs!=40]

array([43, 50, 30, 37])

Logical Operators

In [18]:
#AND operator
np.logical_and(np_weekly_hrs>20,np_weekly_hrs<50)

array([ True, False,  True,  True,  True])