DESCRIPTION

The Iris plant has 3 species - Iris Setosa, Iris Versicolor, and Iris Virginica.
One class is linearly separable from the other two; the latter are not linearly separable from each other.

Objective:
 - Import the Iris dataset using sklearn.
 - Use logistic regression to predict the class of the Iris plant.


In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.datasets import load_iris

In [2]:
data = load_iris()

In [3]:
X = data.data
y = data.target

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [11]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [12]:
pred = lr.predict(X_test)

In [13]:
# confusion matrix
print(confusion_matrix(y_test, pred))

# classfication report
print(classification_report(y_test, pred))

[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [14]:
# accuracy score
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, pred))

0.9666666666666667


In [21]:
# PCA
from sklearn.decomposition import PCA

In [22]:
pca = PCA(n_components=0.95) #pick variables that explain 95% of variance

In [24]:
X_train_transformed = pca.fit_transform(X_train)

In [25]:
# check shape of resulting data
print(X_train_transformed.shape)
print(X_train.shape)

(120, 2)
(120, 4)


In [26]:
# transform testing data set
print(X_test.shape)
X_test_transformed = pca.transform(X_test)
print(X_test_transformed.shape)

(30, 4)
(30, 2)


In [30]:
lr = LogisticRegression(penalty='l2')

In [31]:
lr.fit(X_train_transformed, y_train)

LogisticRegression()

In [32]:
# pred on transformed set
pred = lr.predict(X_test_transformed)

# confusion matrix
print(confusion_matrix(y_test, pred))

# classification report
print(classification_report(y_test, pred))

[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

