In [1]:
# import NumPy library
import numpy as np

In [2]:
#first NumPy array
first_numpy_array = np.array([1,2,3,4])

In [4]:
#print first array
print(first_numpy_array)

[1 2 3 4]


In [6]:
#array with zeros
array_with_zeros = np.zeros((3,3))
print(array_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#array with empty
array_with_empty = np.empty((2,3))
array_with_empty

array([[ 1.28822975e-231, -4.32873677e-311,  1.48219694e-323],
       [ 0.00000000e+000,  0.00000000e+000,  4.17201348e-309]])

In [9]:
#array with arange method
np_arange = np.arange(12)

In [10]:
#print array
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
#reshape method to change/ create array
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
#linspace for linearly (equal) spaced data elements
np_linspace = np.linspace(1,6,5) #first element = 1 | last element = 6 | Total number of equidistant elements = 5

In [13]:
#print linespaced array
print(np_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [14]:
#One dimensional array
oneD_array = np.arange(15)

In [15]:
#print 1D array
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
#Two dimensional array
twoD_array = oneD_array.reshape(3,5)

In [17]:
#print 2D array
print(twoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [18]:
#Three dimensional array
threeD_array = np.arange(27).reshape(3,3,3)

In [19]:
#Print 3D array
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [20]:
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])